DROP DATABASE IF EXISTS `STORAGE`;
CREATE DATABASE `STORAGE`;
USE `STORAGE`;

CREATE TABLE `USER` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`ID`)
);

CREATE TABLE `REGISTEREDUSER` (
  `IDUSER` INT NOT NULL,
  `USERNAME` VARCHAR(45) NOT NULL,
  `PASSWORD` VARCHAR(200) DEFAULT NULL,
  `NAME` VARCHAR(20) DEFAULT NULL,
  `LASTNAME` VARCHAR(20) DEFAULT NULL,
  `EMAIL` VARCHAR(45) DEFAULT NULL,
  `TELEPHONENUMBER` CHAR(10) DEFAULT NULL,
  PRIMARY KEY (`IDUSER`),
  UNIQUE (`USERNAME`),
  KEY `IDUSER_IDX` (`IDUSER`),
  CONSTRAINT `IDUSER_REGISTEREDUSER_FK` FOREIGN KEY (`IDUSER`) REFERENCES `USER` (`ID`) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE `ADMIN` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `USERNAME` VARCHAR(45) NOT NULL,
  `PASSWORD` VARCHAR(200) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE (`USERNAME`)
);

CREATE TABLE `CART` (
  `IDCART` INT NOT NULL,
  PRIMARY KEY (`IDCART`),
  CONSTRAINT `IDCART_CART_FK` FOREIGN KEY (`IDCART`) REFERENCES `USER` (`ID`) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE `PRODUCT` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(45) DEFAULT NULL,
  `PRICE` DOUBLE DEFAULT 0,
  `DISCOUNTPERCENTAGE` DECIMAL(5, 2) DEFAULT NULL,
  `DATEEXPIRATIONDISCOUNT` DATE DEFAULT NULL,
  `DESCRIPTION` VARCHAR(500) DEFAULT NULL,
  `DATEUPLOAD` DATE DEFAULT NULL,
  `SUPPLIER` VARCHAR(45) DEFAULT NULL,
  `CATEGORYNAME` VARCHAR(45) DEFAULT NULL,
  `IMAGEPATH` VARCHAR(100) DEFAULT NULL,
  `QUANTITYAVAILABLE` INT DEFAULT 1,
  PRIMARY KEY (`ID`)
);

CREATE TABLE `PRODUCT_SITUATEDIN_CART` (
  `ID_SITUATEDIN` INT AUTO_INCREMENT PRIMARY KEY,
  `IDCART` INT NOT NULL,
  `IDPRODUCT` INT NOT NULL,
  `DATEADDED` DATE DEFAULT NULL,
  `QUANTITY` INT NOT NULL DEFAULT 1,
  
  KEY `IDCART_IDX` (`IDCART`),
  KEY `IDPRODUCT_IDX` (`IDPRODUCT`),
  CONSTRAINT `IDCART_SITUATEDIN_FK` FOREIGN KEY (`IDCART`) REFERENCES `CART` (`IDCART`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `IDPRODUCT_SITUATEDIN_FK` FOREIGN KEY (`IDPRODUCT`) REFERENCES `PRODUCT` (`ID`) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE `ORDERS` (
  `IDORDER` INT AUTO_INCREMENT PRIMARY KEY,
  `DATEPURCHASE` DATE DEFAULT NULL,
  `DATEDELIVERY` DATE DEFAULT NULL,
  `DATESHIPPING` DATE DEFAULT NULL,
  `IDCART` INT NOT NULL,
  KEY `IDCART_IDX` (`IDCART`),
  CONSTRAINT `IDCART_ORDER_FK` FOREIGN KEY (`IDCART`) REFERENCES `CART` (`IDCART`) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE `PRODUCT_IN_ORDER` (
  `ID_PRODUCT_IN_ORDER` INT AUTO_INCREMENT PRIMARY KEY,
  `IDORDER` INT NOT NULL,
  `IDPRODUCT` INT NOT NULL,
  `QUANTITY` INT DEFAULT 1,
  `PRICE` DOUBLE DEFAULT 0,
  KEY `IDORDER_IDX` (`IDORDER`),
  KEY `IDPRODUCT_IDX` (`IDPRODUCT`),
  CONSTRAINT `IDORDER_IN_ORDER_FK` FOREIGN KEY (`IDORDER`) REFERENCES `ORDERS` (`IDORDER`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `IDPRODUCT_IN_ORDER_FK` FOREIGN KEY (`IDPRODUCT`) REFERENCES `PRODUCT` (`ID`) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE `METHOD_PAYMENT` (
  `PAN` CHAR(19) NOT NULL,
  `EXPIRATIONDATE` CHAR(5) NOT NULL,
  `CVC` VARCHAR(4) NOT NULL,
  PRIMARY KEY (`PAN`)
);

CREATE TABLE `REGISTEREDUSER_HAS_METHOD_PAYMENT` (
  `ID_HAS_METHOD_PAYMENT` INT AUTO_INCREMENT PRIMARY KEY,
  `IDREGISTEREDUSER` INT NOT NULL,
  `PANMETHODPAYMENT` CHAR(19) NOT NULL,
  `EXPIRATIONDATEMETHODPAYMENT` CHAR(5) NOT NULL,
  `CVCMETHODPAYMENT` VARCHAR(4) NOT NULL,
  UNIQUE (`IDREGISTEREDUSER`, `PANMETHODPAYMENT`),
  KEY `IDREGISTEREDUSER_HASMETHODPAYMENT_IDX` (`IDREGISTEREDUSER`),
  KEY `PAN_HASMETHODPAYMENT_IDX` (`PANMETHODPAYMENT`),
  CONSTRAINT `IDREGISTEREDUSER_HASMETHODPAYMENT_FK` FOREIGN KEY (`IDREGISTEREDUSER`) REFERENCES `REGISTEREDUSER` (`IDUSER`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `PAN_HASMETHODPAYMENT_FK` FOREIGN KEY (`PANMETHODPAYMENT`) REFERENCES `METHOD_PAYMENT` (`PAN`) ON UPDATE CASCADE
);

CREATE TABLE `ADDRESS` (
  `NAME` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`NAME`)
);

CREATE TABLE `REGISTEREDUSER_HAS_ADDRESS` (
  `ID_HAS_ADDRESS` INT AUTO_INCREMENT PRIMARY KEY,
  `IDREGISTEREDUSER` INT NOT NULL,
  `NAMEADDRESS` VARCHAR(45) NOT NULL,
  UNIQUE (`IDREGISTEREDUSER`, `NAMEADDRESS`),
  KEY `IDREGISTEREDUSER_HASADDRESS_IDX` (`IDREGISTEREDUSER`),
  KEY `NAMEADDRESS_HASADDRESS_IDX` (`NAMEADDRESS`),
  CONSTRAINT `IDREGISTEREDUSER_HASADDRESS_FK` FOREIGN KEY (`IDREGISTEREDUSER`) REFERENCES `REGISTEREDUSER` (`IDUSER`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `NAMEADDRESS_HASADDRESS_FK` FOREIGN KEY (`NAMEADDRESS`) REFERENCES `ADDRESS` (`NAME`) ON DELETE RESTRICT ON UPDATE CASCADE
);


